import type { Construction } from './constructionsApi'

export const CONSTRUCTIONS_MOCK: Construction[] = [
  {
    id: 1,
    title: 'Частокол',
    use_life: '20 лет',
    description: 'Wooden stockade wall of sharpened logs for defense and perimeter security.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 2,
    title: 'Опорные сваи',
    use_life: '40 лет',
    description: 'Driven timber piles supporting structures on weak or waterlogged ground.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 3,
    title: 'Деревянная кровля',
    use_life: '35 лет',
    description: 'Wooden shingle roof covering with layered boards and ventilated weather protection.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 4,
    title: 'Сруб из бревна',
    use_life: '60 лет',
    description: 'Interlocked log cabin frame with load-bearing walls and durable timber joints.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 5,
    title: 'Деревянная лестница',
    use_life: '35 лет',
    description: 'Solid wood staircase with stable steps and a durable protective finish.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 6,
    title: 'Деревянная дверь',
    use_life: '50 лет',
    description: 'Massive wooden door panel for insulated entryways and interior access.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 7,
    title: 'Палисадник',
    use_life: '10 лет',
    description: 'Light wooden garden fence with treated posts and decorative slat sections.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
  {
    id: 8,
    title: 'Деревянный сруб колодца',
    use_life: '30 лет',
    description: 'Timber well lining that stabilizes the shaft and keeps water access clean.',
    image_url: '',
    video_url: '',
    is_delete: false,
  },
]
